// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwiKJVqEakwalD1drARW30w7CGbfZxE8I',
    appId: '1:75974091374:web:49d95a577c0df5b42a3c7f',
    messagingSenderId: '75974091374',
    projectId: 'flutter-chat-app-220b2',
    authDomain: 'flutter-chat-app-220b2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-220b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLwm99O4zAQOKV_sM2Kc1M_r9x7LmT9w',
    appId: '1:75974091374:android:99ab2b6fc8f500742a3c7f',
    messagingSenderId: '75974091374',
    projectId: 'flutter-chat-app-220b2',
    storageBucket: 'flutter-chat-app-220b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtNAweMJYcYZ79gkkFxVfRqDDtn7V1R-0',
    appId: '1:75974091374:ios:a20f001442d457772a3c7f',
    messagingSenderId: '75974091374',
    projectId: 'flutter-chat-app-220b2',
    storageBucket: 'flutter-chat-app-220b2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtNAweMJYcYZ79gkkFxVfRqDDtn7V1R-0',
    appId: '1:75974091374:ios:a20f001442d457772a3c7f',
    messagingSenderId: '75974091374',
    projectId: 'flutter-chat-app-220b2',
    storageBucket: 'flutter-chat-app-220b2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwiKJVqEakwalD1drARW30w7CGbfZxE8I',
    appId: '1:75974091374:web:9c88f7f55a17b8632a3c7f',
    messagingSenderId: '75974091374',
    projectId: 'flutter-chat-app-220b2',
    authDomain: 'flutter-chat-app-220b2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-220b2.firebasestorage.app',
  );
}
